condtion_Dr_matching = {
    "Allergy": 'drKen',
    "GERD": 'drCandice',
    "AIDS": 'drBrown',
    "Diabetes": 'drWhite',
    "Gastroenteritis": 'drBlue',
    "Hypertension": 'drEvans',
    "Migraine": 'drJane',
    "Jaundice": 'drEast',
    "Malaria": 'drJude',
    "Dengue": 'drKen',
    "Typhoid": 'drCandice',
    "hepatitis A": 'drBrown',
    "Hepatitis B": 'drWhite',
    "Hepatitis C": 'drBlue',
    "Hepatitis D": 'drEvans',
    "Hepatitis E": 'drJane',
    "Tuberculosis": 'drEast',
    "Pneumonia": 'drJude',
    "Hypothyroidism": 'drBrown',
    "Hyperthyroidism": 'drWhite',
    "Hypoglycemia": 'drBlue',
    "Osteoarthristis": 'drEvans',
    "Arthritis": 'drJane',
    "Acne": 'drEast',
    "Psoriasis": 'drJude',
    "Impetigo": 'drBrown'
}

